### ISSUE TITLE
关于Skill Summer Healing的建议

### ISSUE THREAD

**Issue by Ninecloud2077** [StarOnTheSky/mmotee_cn#1]
1.合成Skill Summer Healing时候，建议加上一个保底：
合成24次失败后第25次必定成功。
2.建议在合成栏给Skill Summer Healing加上注释：
4%概率合成成功—合成25次必定成功。

**Comment by phone-burner** [comment]
已加入,保底数量为 15 次

**Comment by Ninecloud2077** [comment]
好吧我觉得featrue没有拼错
