### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by kurosio** [StarOnTheSky/mmotee_cn#14]
Any contacts for people on discord who are currently working on the mod?
I have time for now, want to help.

**Comment by ST-Chara** [comment]
(I am FlowerFell-Sans  You can call me FFS, which is an abbreviation of my full name, FlowerFell-Sans.)

**Comment by kurosio** [comment]
@StarOnTheSky I'll even say there are a lot of problems there. I'm also surprised that it works. And there is no optimization there at all. Packets are sent to everyone, regardless of whether it is a bot or not. But players have to accept these packets anyway

**Comment by kurosio** [comment]
@StarOnTheSky, do you compile through bam?

**Comment by kurosio** [comment]
@StarOnTheSky If you will need help, can contact (discord only : kurosio#9680)
