### ISSUE TITLE
居然都让我翻到这来了。。。

### ISSUE THREAD

**Issue by gongfuture** [StarOnTheSky/mmotee_cn#23]
所以说现在这玩意还有人在运营维护嘛？上次在群里提问题都没有能答复的

**Comment by Ninecloud2077** [comment]
TeeworldsCN关了 现在是StarOnTheSky主管
但是她现在高考 考完又有一些事 所以一直没太活跃
次一点的管理有我和王小睿 john什么的也没再管了

**Comment by gongfuture** [comment]
Okok

从 Windows 版邮件发送

发件人: Ninecloud2077
发送时间: 2022年8月21日 21:11
收件人: StarOnTheSky/mmotee_cn
抄送: gongfuture; Author
主题: Re: [StarOnTheSky/mmotee_cn] 居然都让我翻到这来了。。。 (Issue #23)

TeeworldsCN关了 现在是StarOnTheSky主管
但是她现在高考 考完又有一些事 所以一直没太活跃
次一点的管理有我和王小睿 john什么的也没再管了
